vo=gpu
gpu-api=opengl
really-quiet=yes
msg-level=statusline=status
term-status-msg="${?pause==yes:(Paused) }AV: ${time-pos} / ${duration} (${percent-pos}%)"
title="${media-title}"
keep-open=yes

sub-font="Noto Sans"
sub-font-size=48
sub-bold=yes
sub-border-size=2
sub-shadow-offset=1
sub-margin-y=30
