gui: 
 authorColors:
    'darianmorat': 'blue'
    '*': 'blue'    
  border: single
  showBottomLine: false
  showPanelJumps: false
  commandLogSize: 1
  theme:
    activeBorderColor:
      - white
      - bold
    selectedLineBgColor:
      - "#444444"

git:
  paging:
    pager: ""
    externalDiffCommand: ""
  commitPrefix:
    pattern: " " 
    replace: " "    
