gui:
  border: single
  showBottomLine: false
  showCommandLog: false
  showPanelJumps: false
  colorScheme: dark
  theme:
    authorColors:
      'Darian Toledo': 'cyan'
  darkTheme:
    selectedLineBgColor:
      - "#303030"
    inactiveBorderColor:
      - "#5F5F5F"
  lightTheme:
    selectedLineBgColor:
      - "#C9C9BF"
    inactiveBorderColor:
      - "#7F7F7F"
notARepository: 'quit'
customCommands:
  - key: "w"
    command: "git cz; true"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    output: terminal
git:
  diffRenderers:
    - command: delta --paging=never
    - type: extDiff
      command: difft --color=always --display=inline --syntax-highlight=off --context={{diffContext}}
    - name: default
      type: rawGit
