gui: 
 authorColors:
    'darianmorat': 'blue'
    '*': 'blue'    
  border: single
  showBottomLine: false
  showPanelJumps: false
  commandLogSize: 1
  theme:
    activeBorderColor:
      - white
      - bold
    selectedLineBgColor:
      - "#444444" # Dark theme
      # - "#d4d2c7" # Light theme

git:
  paging:
    pager: ""
    externalDiffCommand: ""
  commitPrefix:
    pattern: " " 
    replace: " "    

customCommands:
  - key: "w"
    command: "git cz"
    description: "commit with commitizen"
    context: "files"
    loadingText: "opening commitizen commit tool"
    subprocess: true
