#!/usr/local/bin/zsh

theme-manager() {
   local CURRENT_THEME_FILE="$HOME/.config/current_theme"
   local CONFIG_DIR="$HOME/.config"
   local GTK_CONFIG="$CONFIG_DIR/gtk-3.0/settings.ini"

   # Toggle
   local current=$([ -f "$CURRENT_THEME_FILE" ] && cat "$CURRENT_THEME_FILE" || echo "dark")
   if [ "$1" = "init" ]; then
      local theme="$current"
   else
      local theme=$([ "$current" = "dark" ] && echo "light" || echo "dark")
      echo "$theme" > "$CURRENT_THEME_FILE"
   fi

   # Save and export
   export THEME_MODE="$theme"

   # GTK
   local gtk_theme=$([ "$theme" = "dark" ] && echo "Materia-dark" || echo "Materia-light")
   sed -i "s|gtk-theme-name=.*|gtk-theme-name=$gtk_theme|" "$GTK_CONFIG"
   gsettings set org.gnome.desktop.interface color-scheme "prefer-$theme"

   # Live change open apps
   XSETTINGS="$HOME/.config/xsettingsd/xsettingsd.conf"
   sed -i "s|Net/ThemeName .*|Net/ThemeName \"$gtk_theme\"|" "$XSETTINGS"
   pkill -HUP xsettingsd 2>/dev/null || xsettingsd &

   # Background
   if [ "$theme" = "dark" ]; then
      hsetroot -solid "#1E1E1E"
   else
      hsetroot -solid "#F7F5EA"
   fi

   # Lazygit
   if [ "$theme" = "dark" ]; then
      lg_color="#303030"
   else
      lg_color="#C9C9BF"
   fi
   sed -i "s/- \"#[^\"]*\"/- \"$lg_color\"/" "$CONFIG_DIR/lazygit/config.yml"

   # FZF
   if [ "$theme" = "dark" ]; then
      fzf_opts="--ansi
      --layout=reverse
      --border=none
      --preview-window=border-sharp
      --info=inline-right
      --highlight-line
      --color=scrollbar:#1E1E1E
      --color=fg:#D6CFC4
      --color=fg+:#E6E3DE
      --color=bg:#1E1E1E
      --color=bg+:#303030
      --color=gutter:#1E1E1E
      --color=prompt:#579DD4
      --color=marker:#B55353
      --color=pointer:#B55353
      --color=header:#D19F66
      --color=info:#575757
      --color=hl:#72BA62
      --color=hl+:#72BA62
      --color=query:#D6CFC4"
   else
      fzf_opts="--ansi
      --layout=reverse
      --border=none
      --preview-window=border-sharp
      --info=inline-right
      --highlight-line
      --color=scrollbar:#F7F5EA
      --color=fg:#070707
      --color=fg+:#000000
      --color=bg:#F7F5EA
      --color=bg+:#C9C9BF
      --color=gutter:#F7F5EA
      --color=prompt:#0F5289
      --color=marker:#AD4B4B
      --color=pointer:#AD4B4B
      --color=header:#AE5F05
      --color=info:#707070
      --color=hl:#006C00
      --color=hl+:#006C00
      --color=query:#101010"
   fi
   echo "$fzf_opts" > ~/.fzfrc

   # WezTerm
   touch ~/.config/wezterm/wezterm.lua

   # Indicator for i3
   if [ "$theme" = "dark" ]; then
      i3_indicator="#FFFFFF"
   else
      i3_indicator="#2E9EF4"
   fi

   sed -i "s|client.focused .*|client.focused          #181818 #131313 #FFFFFF $i3_indicator   #181818|" "$HOME/.config/i3/config"

   # Reload i3 and notify
   if [ "$1" != "init" ]; then
      i3-msg reload
      notify-send "Theme switched to $theme"
   fi
}

theme-manager "$@"
